resolver: lts-10.1

packages:
  - '.'
  - 'tensorflow-mnist-deptyped'
  - 'tensorflow-deptyped-examples'
  - location:
      git: https://github.com/tensorflow/haskell.git
      commit: a8405d15a22fc62dce8e868623e12a83e11f56b8
    subdirs:
      - tensorflow
      - tensorflow-core-ops
      - tensorflow-logging
      - tensorflow-mnist
      - tensorflow-mnist-input-data
      - tensorflow-opgen
      - tensorflow-ops
      - tensorflow-proto
      - tensorflow-records
      - tensorflow-records-conduit
      - tensorflow-test
    extra-dep: true

extra-deps:
  - snappy-0.2.0.2
  - snappy-framing-0.1.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

nix:
  # enable: true
  packages: [glpk, pcre, zlib, protobuf, snappy]

# extra-lib-dirs:
#     - /usr/lib
# extra-include-dirs:
#     - /usr/include
